namespace Oak.Valkyrie.AST;

/// <summary>
///     AST 节点类型枚举，用于运行时按类型判别而不依赖反射
/// </summary>
/// <para>每种 AST 节点对应一个枚举值，通过 <see cref="ValkyrieNode.Type"/> 属性获取</para>
public enum ValkyrieNodeType
{
    /// <summary>
    ///     未知节点类型（出错或未匹配时的默认值）
    /// </summary>
    Unknown = -1,

    CompilationUnit,
    ComponentDecl,
    SystemDecl,
    WidgetDecl,
    FunctionDecl,
    BlockStmt,
    IfStmt,
    LoopStatement,
    MetaExprInterpolation,
    MetaLoopStmt,
    MetaForeachStmt,
    MetaIfStmt,
    MetaMatchStmt,
    MacroRefExpr,
    MetaTemplateText,
    StructDecl,
    ForStmt,
    DiscardStmt,
    SwizzleExpr,
    UsingDecl,
    UniformBindingDecl,
    EnumDecl,
    FlagsDecl,
    UnionDecl,
    UniteDecl,
    StorageDecl,
    ServiceDecl,
    DomainDecl,
    MetaDecl,
    NamespaceDecl,
    VariableDecl,
    FieldDecl,
    ParameterDecl,
    ImportDecl,
    AttributeDecl,
    DocCommentDecl,
    TypeAliasDecl,
    NeuralDecl,
    ClassDecl,
    ShaderDecl,
    VaryingDecl,
    ConstantBufferDecl,
    TextureDecl,
    SamplerDecl,
    ShaderAttributeDecl,
    TypeAnnotation,
    LiteralExpr,
    BinaryExpr,
    AssignmentExpr,
    MemberAccessExpr,
    QualifiedPathExpr,
    IdentifierNode,
    UnaryExpr,
    LambdaExpr,
    QueryExpr,
    TermCallExpression,
    TermIndexExpression,
    OrdinalIndexExpression,
    OffsetIndexExpression,
    BlockExpr,
    IfStatement,
    MatchStmt,
    ReturnStatement,
    ResumeStmt,
    TermExpressionStatement,
    WhileStatement,
    CatchStmt,
    ChannelConditionalDecl,
    HalDecl,
    PalDecl,
    TraitDecl,
    IsExpr,
    AsExpr,
    CastExpr,
    OrPattern,
    GuardedPattern,
}
