using System.Text;
using Oak.DejaVu.Expressions;

namespace Oak.DejaVu.CodeGen;

/// <summary>
///     Java 代码生成器——将 DejaVu 模板 AST 转译为 Java 渲染类源码。
///     输出可在 JVM 中直接编译执行的 Java 代码。
/// </summary>
public sealed class JavaCodeGenerator
{
    private int _indentLevel;

    /// <summary>
    ///     创建 Java 代码生成器
    /// </summary>
    public JavaCodeGenerator()
    {
        Options = new JavaGeneratorOptions();
    }

    /// <summary>
    ///     创建 Java 代码生成器
    /// </summary>
    /// <param name="options">生成选项</param>
    public JavaCodeGenerator(JavaGeneratorOptions options)
    {
        Options = options;
    }

    /// <summary>
    ///     生成选项
    /// </summary>
    public JavaGeneratorOptions Options { get; }

    /// <summary>
    ///     生成 Java 渲染类源码
    /// </summary>
    /// <param name="nodes">优化后的模板节点列表</param>
    /// <param name="className">类名</param>
    /// <returns>Java 源码</returns>
    public string Generate(IReadOnlyList<DejaVuTemplateNode> nodes, string className = "TemplateRenderer")
    {
        var sb = new StringBuilder();

        GenerateHeader(sb);
        GenerateClassHeader(sb, className);
        GenerateRenderMethod(sb, nodes);
        GenerateHelperMethods(sb);
        GenerateClassFooter(sb);

        return sb.ToString();
    }

    private void GenerateHeader(StringBuilder sb)
    {
        if (Options.IncludeHeader)
        {
            sb.AppendLine("// Auto-generated by DejaVu Java Code Generator");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine();
        }

        sb.AppendLine("import java.util.*;");
        sb.AppendLine("import java.util.stream.*;");
        sb.AppendLine();
    }

    private void GenerateClassHeader(StringBuilder sb, string className)
    {
        sb.AppendLine($"public class {className} {{");
        _indentLevel = 1;
    }

    private void GenerateClassFooter(StringBuilder sb)
    {
        _indentLevel = 0;
        sb.AppendLine("}");
    }

    private void GenerateRenderMethod(StringBuilder sb, IReadOnlyList<DejaVuTemplateNode> nodes)
    {
        Indent(sb);
        sb.AppendLine("public String render(Map<String, Object> ctx) {");
        _indentLevel++;

        Indent(sb);
        sb.AppendLine("StringBuilder sb = new StringBuilder();");

        foreach (var node in nodes)
        {
            GenerateNode(sb, node, "ctx", "sb");
        }

        Indent(sb);
        sb.AppendLine("return sb.toString();");

        _indentLevel--;
        Indent(sb);
        sb.AppendLine("}");
    }

    private void GenerateNode(StringBuilder sb, DejaVuTemplateNode node, string ctxVar, string sbVar)
    {
        switch (node)
        {
            case DejaVuTextNode textNode:
                GenerateTextNode(sb, textNode, sbVar);
                break;
            case DejaVuCodeNode codeNode:
                GenerateCodeNode(sb, codeNode, ctxVar, sbVar);
                break;
            case DejaVuIfNode ifNode:
                GenerateIfNode(sb, ifNode, ctxVar, sbVar);
                break;
            case DejaVuLoopNode loopNode:
                GenerateLoopNode(sb, loopNode, ctxVar, sbVar);
                break;
            case DejaVuLetNode letNode:
                GenerateLetNode(sb, letNode, ctxVar, sbVar);
                break;
            case DejaVuWithNode withNode:
                GenerateWithNode(sb, withNode, ctxVar, sbVar);
                break;
            case DejaVuBlockNode blockNode:
                GenerateBlockNode(sb, blockNode, ctxVar, sbVar);
                break;
            case DejaVuIncludeNode includeNode:
                GenerateIncludeNode(sb, includeNode, ctxVar, sbVar);
                break;
            case DejaVuSuperNode:
                GenerateSuperNode(sb, sbVar);
                break;
            case DejaVuRawNode rawNode:
                GenerateRawNode(sb, rawNode, ctxVar, sbVar);
                break;
            case DejaVuMatchNode matchNode:
                GenerateMatchNode(sb, matchNode, ctxVar, sbVar);
                break;
            case DejaVuExtendsNode extendsNode:
                GenerateExtendsNode(sb, extendsNode);
                break;
        }
    }

    private void GenerateTextNode(StringBuilder sb, DejaVuTextNode textNode, string sbVar)
    {
        var escaped = EscapeJavaString(textNode.Text);
        Indent(sb);
        sb.AppendLine($"{sbVar}.append(\"{escaped}\");");
    }

    private void GenerateCodeNode(StringBuilder sb, DejaVuCodeNode codeNode, string ctxVar, string sbVar)
    {
        var expr = GenerateExpression(codeNode.ParsedExpression, codeNode.Code, ctxVar);
        Indent(sb);
        sb.AppendLine($"{sbVar}.append(escapeHtml(String.valueOf({expr})));");
    }

    private void GenerateIfNode(StringBuilder sb, DejaVuIfNode ifNode, string ctxVar, string sbVar)
    {
        var condition = GenerateExpression(ifNode.ParsedCondition, ifNode.Condition, ctxVar);
        Indent(sb);
        sb.AppendLine($"if (toBoolean({condition})) {{");

        _indentLevel++;
        foreach (var child in ifNode.Children)
        {
            GenerateNode(sb, child, ctxVar, sbVar);
        }

        _indentLevel--;

        foreach (var elseIfNode in ifNode.ElseIfNodes)
        {
            var elseIfCondition = GenerateExpression(elseIfNode.ParsedCondition, elseIfNode.Condition, ctxVar);
            Indent(sb);
            sb.AppendLine($"}} else if (toBoolean({elseIfCondition})) {{");

            _indentLevel++;
            foreach (var child in elseIfNode.Children)
            {
                GenerateNode(sb, child, ctxVar, sbVar);
            }

            _indentLevel--;
        }

        if (ifNode.ElseChildren.Count > 0)
        {
            Indent(sb);
            sb.AppendLine("} else {");

            _indentLevel++;
            foreach (var child in ifNode.ElseChildren)
            {
                GenerateNode(sb, child, ctxVar, sbVar);
            }

            _indentLevel--;
        }

        Indent(sb);
        sb.AppendLine("}");
    }

    private void GenerateLoopNode(StringBuilder sb, DejaVuLoopNode loopNode, string ctxVar, string sbVar)
    {
        var iterable = GenerateExpression(loopNode.ParsedExpression, loopNode.Expression, ctxVar);
        var itemName = loopNode.ItemName ?? "item";
        var javaItemName = ToJavaIdentifier(itemName);

        Indent(sb);
        sb.AppendLine($"for (Object {javaItemName} : toIterable({iterable})) {{");

        _indentLevel++;
        Indent(sb);
        sb.AppendLine($"Map<String, Object> __loopCtx = new HashMap<>({ctxVar});");
        Indent(sb);
        sb.AppendLine($"__loopCtx.put(\"{itemName}\", {javaItemName});");
        Indent(sb);
        sb.AppendLine($"__loopCtx.put(\"index\", __loopIndex++);");

        foreach (var child in loopNode.Children)
        {
            GenerateNode(sb, child, "__loopCtx", sbVar);
        }

        _indentLevel--;
        Indent(sb);
        sb.AppendLine("}");
    }

    private void GenerateLetNode(StringBuilder sb, DejaVuLetNode letNode, string ctxVar, string sbVar)
    {
        var value = GenerateExpression(letNode.ParsedExpression, letNode.Expression, ctxVar);

        Indent(sb);
        sb.AppendLine($"Map<String, Object> __letCtx = new HashMap<>({ctxVar});");
        Indent(sb);
        sb.AppendLine($"__letCtx.put(\"{letNode.VariableName}\", {value});");

        foreach (var child in letNode.Children)
        {
            GenerateNode(sb, child, "__letCtx", sbVar);
        }
    }

    private void GenerateWithNode(StringBuilder sb, DejaVuWithNode withNode, string ctxVar, string sbVar)
    {
        var obj = GenerateExpression(withNode.ParsedExpression, withNode.Expression, ctxVar);

        Indent(sb);
        sb.AppendLine($"Object __withObj = {obj};");
        Indent(sb);
        sb.AppendLine($"Map<String, Object> __withCtx = new HashMap<>({ctxVar});");
        Indent(sb);
        sb.AppendLine("if (__withObj instanceof Map) { __withCtx.putAll((Map<?, ?>) __withObj); }");

        foreach (var child in withNode.Children)
        {
            GenerateNode(sb, child, "__withCtx", sbVar);
        }
    }

    private void GenerateBlockNode(StringBuilder sb, DejaVuBlockNode blockNode, string ctxVar, string sbVar)
    {
        Indent(sb);
        sb.AppendLine($"// block: {blockNode.Name}");

        foreach (var child in blockNode.Children)
        {
            GenerateNode(sb, child, ctxVar, sbVar);
        }
    }

    private void GenerateIncludeNode(StringBuilder sb, DejaVuIncludeNode includeNode, string ctxVar, string sbVar)
    {
        var path = includeNode.TemplatePath.Trim('\'', '"');
        Indent(sb);
        sb.AppendLine($"{sbVar}.append(renderInclude({ctxVar}, \"{EscapeJavaString(path)}\"));");
    }

    private void GenerateSuperNode(StringBuilder sb, string sbVar)
    {
        Indent(sb);
        sb.AppendLine($"{sbVar}.append(renderSuper(ctx));");
    }

    private void GenerateRawNode(StringBuilder sb, DejaVuRawNode rawNode, string ctxVar, string sbVar)
    {
        foreach (var child in rawNode.Children)
        {
            if (child is DejaVuTextNode textNode)
            {
                var escaped = EscapeJavaString(textNode.Text);
                Indent(sb);
                sb.AppendLine($"{sbVar}.append(\"{escaped}\");");
            }
            else if (child is DejaVuCodeNode codeNode)
            {
                var expr = GenerateExpression(codeNode.ParsedExpression, codeNode.Code, ctxVar);
                Indent(sb);
                sb.AppendLine($"{sbVar}.append(String.valueOf({expr}));");
            }
        }
    }

    private void GenerateMatchNode(StringBuilder sb, DejaVuMatchNode matchNode, string ctxVar, string sbVar)
    {
        var matchExpr = GenerateExpression(matchNode.ParsedExpression, matchNode.Expression, ctxVar);
        Indent(sb);
        sb.AppendLine($"Object __matchVal = {matchExpr};");

        var isFirst = true;
        foreach (var child in matchNode.Children)
        {
            if (child is DejaVuIfNode ifNode)
            {
                var condition = GenerateExpression(ifNode.ParsedCondition, ifNode.Condition, ctxVar);
                var keyword = isFirst ? "if" : "} else if";
                Indent(sb);
                sb.AppendLine($"{keyword} (areEqual(__matchVal, {condition})) {{");

                _indentLevel++;
                foreach (var ifChild in ifNode.Children)
                {
                    GenerateNode(sb, ifChild, ctxVar, sbVar);
                }

                _indentLevel--;
                isFirst = false;
            }
        }

        if (!isFirst)
        {
            Indent(sb);
            sb.AppendLine("}");
        }
    }

    private void GenerateExtendsNode(StringBuilder sb, DejaVuExtendsNode extendsNode)
    {
        var parent = extendsNode.ParentTemplate.Trim('\'', '"');
        Indent(sb);
        sb.AppendLine($"// extends: {EscapeJavaString(parent)}");
    }

    private string GenerateExpression(IExpressionNode? parsedAst, string fallback, string ctxVar)
    {
        if (parsedAst != null)
        {
            return GenerateExpressionNode(parsedAst, ctxVar);
        }

        return $"evalExpr({ctxVar}, \"{EscapeJavaString(fallback)}\")";
    }

    private string GenerateExpressionNode(IExpressionNode node, string ctxVar)
    {
        return node switch
        {
            LiteralNode lit => GenerateLiteral(lit),
            IdentifierNode id => $"({ctxVar}.get(\"{id.Name}\"))",
            BinaryNode binary => GenerateBinary(binary, ctxVar),
            UnaryNode unary => GenerateUnary(unary, ctxVar),
            MemberAccessNode member => GenerateMemberAccess(member, ctxVar),
            CallNode call => GenerateCall(call, ctxVar),
            IndexNode index => GenerateIndex(index, ctxVar),
            PipeNode pipe => GeneratePipe(pipe, ctxVar),
            _ => "null"
        };
    }

    private string GenerateLiteral(LiteralNode lit)
    {
        return lit.Value switch
        {
            null => "null",
            bool b => b ? "true" : "false",
            double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture) + "d",
            string s => $"\"{EscapeJavaString(s)}\"",
            _ => $"\"{EscapeJavaString(lit.Value.ToString())}\""
        };
    }

    private string GenerateBinary(BinaryNode binary, string ctxVar)
    {
        var left = GenerateExpressionNode(binary.Left, ctxVar);
        var right = GenerateExpressionNode(binary.Right, ctxVar);

        return binary.Operator switch
        {
            BinaryOperator.Add => $"addObjects({left}, {right})",
            BinaryOperator.Subtract => $"subtractObjects({left}, {right})",
            BinaryOperator.Multiply => $"multiplyObjects({left}, {right})",
            BinaryOperator.Divide => $"divideObjects({left}, {right})",
            BinaryOperator.Modulo => $"moduloObjects({left}, {right})",
            BinaryOperator.Equal => $"Objects.equals({left}, {right})",
            BinaryOperator.NotEqual => $"(!Objects.equals({left}, {right}))",
            BinaryOperator.LessThan => $"lessThan({left}, {right})",
            BinaryOperator.LessThanOrEqual => $"lessThanOrEqual({left}, {right})",
            BinaryOperator.GreaterThan => $"greaterThan({left}, {right})",
            BinaryOperator.GreaterThanOrEqual => $"greaterThanOrEqual({left}, {right})",
            BinaryOperator.And => $"(toBoolean({left}) && toBoolean({right}))",
            BinaryOperator.Or => $"(toBoolean({left}) || toBoolean({right}))",
            _ => "null"
        };
    }

    private string GenerateUnary(UnaryNode unary, string ctxVar)
    {
        var operand = GenerateExpressionNode(unary.Operand, ctxVar);
        return unary.Operator switch
        {
            UnaryOperator.Negate => $"negateObject({operand})",
            UnaryOperator.Not => $"(!toBoolean({operand}))",
            _ => operand
        };
    }

    private string GenerateMemberAccess(MemberAccessNode member, string ctxVar)
    {
        var obj = GenerateExpressionNode(member.Object, ctxVar);
        return $"memberAccess({obj}, \"{member.MemberName}\")";
    }

    private string GenerateCall(CallNode call, string ctxVar)
    {
        var func = GenerateExpressionNode(call.Function, ctxVar);
        var args = string.Join(", ", call.Arguments.Select(a => GenerateExpressionNode(a, ctxVar)));
        return $"callFunction({func}{(string.IsNullOrEmpty(args) ? "" : $", {args}")})";
    }

    private string GenerateIndex(IndexNode index, string ctxVar)
    {
        var obj = GenerateExpressionNode(index.Object, ctxVar);
        var idx = GenerateExpressionNode(index.Index, ctxVar);
        return $"indexAccess({obj}, {idx})";
    }

    private string GeneratePipe(PipeNode pipe, string ctxVar)
    {
        var left = GenerateExpressionNode(pipe.Left, ctxVar);
        var args = string.Join(", ", pipe.Arguments.Select(a => GenerateExpressionNode(a, ctxVar)));
        return $"applyFilter(\"{pipe.FilterName}\", {left}{(string.IsNullOrEmpty(args) ? "" : $", {args}")})";
    }

    private void GenerateHelperMethods(StringBuilder sb)
    {
        if (!Options.EmitHelpersInline)
        {
            return;
        }

        _indentLevel = 1;

        Indent(sb);
        sb.AppendLine("private int __loopIndex = 0;");
        sb.AppendLine();

        GenerateHelperMethod(sb, "escapeHtml", "String", "String input",
            "if (input == null) return \"\";",
            "return input",
            "    .replace(\"&\", \"&amp;\")",
            "    .replace(\"<\", \"&lt;\")",
            "    .replace(\">\", \"&gt;\")",
            "    .replace(\"\\\"\", \"&quot;\")",
            "    .replace(\"'\", \"&#x27;\");");

        GenerateHelperMethod(sb, "toBoolean", "boolean", "Object value",
            "if (value == null) return false;",
            "if (value instanceof Boolean) return (Boolean) value;",
            "return true;");

        GenerateHelperMethod(sb, "toIterable", "Iterable<?>", "Object value",
            "if (value instanceof Iterable) return (Iterable<?>) value;",
            "if (value instanceof Map) return ((Map<?, ?>) value).values();",
            "return Collections.emptyList();");

        GenerateHelperMethod(sb, "areEqual", "boolean", "Object a, Object b",
            "if (a == null && b == null) return true;",
            "if (a == null || b == null) return false;",
            "return a.equals(b);");

        GenerateHelperMethod(sb, "memberAccess", "Object", "Object obj, String member",
            "if (obj instanceof Map) return ((Map<?, ?>) obj).get(member);",
            "try {",
            "    var field = obj.getClass().getField(member);",
            "    return field.get(obj);",
            "} catch (Exception e) { return null; }");

        GenerateHelperMethod(sb, "indexAccess", "Object", "Object obj, Object index",
            "if (obj instanceof List) { int i = ((Number) index).intValue(); var list = (List<?>) obj; return i >= 0 && i < list.size() ? list.get(i) : null; }",
            "if (obj instanceof Map) return ((Map<?, ?>) obj).get(index);",
            "return null;");

        GenerateHelperMethod(sb, "callFunction", "Object", "Object func, Object... args",
            "if (func instanceof java.util.function.Function) return ((java.util.function.Function<Object, Object>) func).apply(args.length > 0 ? args[0] : null);",
            "return null;");

        GenerateHelperMethod(sb, "addObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() + ((Number) b).doubleValue();",
            "return String.valueOf(a) + String.valueOf(b);");

        GenerateHelperMethod(sb, "subtractObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() - ((Number) b).doubleValue();",
            "return 0d;");

        GenerateHelperMethod(sb, "multiplyObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() * ((Number) b).doubleValue();",
            "return 0d;");

        GenerateHelperMethod(sb, "divideObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) { double bv = ((Number) b).doubleValue(); return bv != 0 ? ((Number) a).doubleValue() / bv : 0d; }",
            "return 0d;");

        GenerateHelperMethod(sb, "moduloObjects", "Object", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) { double bv = ((Number) b).doubleValue(); return bv != 0 ? ((Number) a).doubleValue() % bv : 0d; }",
            "return 0d;");

        GenerateHelperMethod(sb, "negateObject", "Object", "Object a",
            "if (a instanceof Number) return -((Number) a).doubleValue();",
            "return 0d;");

        GenerateHelperMethod(sb, "lessThan", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() < ((Number) b).doubleValue();",
            "return false;");

        GenerateHelperMethod(sb, "lessThanOrEqual", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() <= ((Number) b).doubleValue();",
            "return false;");

        GenerateHelperMethod(sb, "greaterThan", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() > ((Number) b).doubleValue();",
            "return false;");

        GenerateHelperMethod(sb, "greaterThanOrEqual", "boolean", "Object a, Object b",
            "if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() >= ((Number) b).doubleValue();",
            "return false;");

        GenerateFilterMethod(sb);
    }

    private void GenerateHelperMethod(StringBuilder sb, string name, string returnType, string params_, params string[] bodyLines)
    {
        Indent(sb);
        sb.AppendLine($"private static {returnType} {name}({params_}) {{");
        _indentLevel++;
        foreach (var line in bodyLines)
        {
            Indent(sb);
            sb.AppendLine(line);
        }

        _indentLevel--;
        Indent(sb);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void GenerateFilterMethod(StringBuilder sb)
    {
        Indent(sb);
        sb.AppendLine("private static Object applyFilter(String name, Object value, Object... args) {");
        _indentLevel++;
        Indent(sb);
        sb.AppendLine("switch (name) {");

        var filters = new (string Name, string Body)[]
        {
            ("uppercase", "return String.valueOf(value).toUpperCase();"),
            ("lowercase", "return String.valueOf(value).toLowerCase();"),
            ("trim", "return String.valueOf(value).trim();"),
            ("capitalize", "String s = String.valueOf(value); return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);"),
            ("truncate", "int len = args.length > 0 ? ((Number) args[0]).intValue() : 30; String s = String.valueOf(value); return s.length() > len ? s.substring(0, len) + \"...\" : s;"),
            ("default", "return (value == null || \"\".equals(value)) ? (args.length > 0 ? args[0] : null) : value;"),
            ("join", "if (value instanceof Iterable) { String sep = args.length > 0 ? String.valueOf(args[0]) : \", \"; return StreamSupport.stream(((Iterable<?>) value).spliterator(), false).map(String::valueOf).collect(Collectors.joining(sep)); } return String.valueOf(value);"),
            ("length", "if (value instanceof Collection) return ((Collection<?>) value).size(); return String.valueOf(value).length();"),
            ("first", "if (value instanceof Iterable) { var it = ((Iterable<?>) value).iterator(); return it.hasNext() ? it.next() : null; } return null;"),
            ("last", "if (value instanceof List) { var list = (List<?>) value; return list.isEmpty() ? null : list.get(list.size() - 1); } return null;"),
            ("reverse", "if (value instanceof List) { var list = new ArrayList<>((List<?>) value); Collections.reverse(list); return list; } return new StringBuilder(String.valueOf(value)).reverse().toString();"),
            ("sort", "if (value instanceof List) { var list = new ArrayList<>((List<?>) value); Collections.sort(list, (a, b) -> String.valueOf(a).compareTo(String.valueOf(b))); return list; } return value;"),
            ("strip_html", "return String.valueOf(value).replaceAll(\"<[^>]*>\", \"\");"),
            ("escape", "return escapeHtml(String.valueOf(value));"),
            ("newline_to_br", "return String.valueOf(value).replace(\"\\n\", \"<br/>\");"),
            ("abs", "return value instanceof Number ? Math.abs(((Number) value).doubleValue()) : value;"),
            ("round", "int d = args.length > 0 ? ((Number) args[0]).intValue() : 0; return value instanceof Number ? Math.round(((Number) value).doubleValue() * Math.pow(10, d)) / Math.pow(10, d) : value;"),
            ("floor", "return value instanceof Number ? Math.floor(((Number) value).doubleValue()) : value;"),
            ("ceil", "return value instanceof Number ? Math.ceil(((Number) value).doubleValue()) : value;"),
            ("count", "if (value instanceof Collection) return ((Collection<?>) value).size(); if (value instanceof String) return ((String) value).length(); return 0;"),
            ("safe", "return value;"),
            ("date", "if (value instanceof java.time.temporal.Temporal) return value.toString(); return String.valueOf(value);"),
            ("datetime", "if (value instanceof java.time.temporal.Temporal) return value.toString(); return String.valueOf(value);"),
        };

        foreach (var (name, body) in filters)
        {
            _indentLevel++;
            Indent(sb);
            sb.AppendLine($"case \"{name}\": {body}");
            _indentLevel--;
        }

        Indent(sb);
        sb.AppendLine("default: return value;");
        Indent(sb);
        sb.AppendLine("}");

        _indentLevel--;
        Indent(sb);
        sb.AppendLine("}");
    }

    private void Indent(StringBuilder sb)
    {
        sb.Append(new string(' ', _indentLevel * Options.IndentSize));
    }

    private static string EscapeJavaString(string? input)
    {
        if (input == null) return string.Empty;
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private static string ToJavaIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "item";
        if (char.IsDigit(name[0])) return "_" + name;
        return name;
    }
}

/// <summary>
///     Java 代码生成选项
/// </summary>
public sealed class JavaGeneratorOptions
{
    /// <summary>
    ///     是否包含文件头注释
    /// </summary>
    public bool IncludeHeader { get; init; } = true;

    /// <summary>
    ///     是否内联辅助方法
    /// </summary>
    public bool EmitHelpersInline { get; init; } = true;

    /// <summary>
    ///     缩进空格数
    /// </summary>
    public int IndentSize { get; init; } = 4;
}
