using System.Text;
using Oak.DejaVu.Expressions;

namespace Oak.DejaVu.CodeGen;

/// <summary>
///     TypeScript 代码生成器——将 DejaVu 模板 AST 转译为 TypeScript 渲染函数源码。
///     输出可在浏览器/Node.js 中直接执行的 TypeScript 代码。
/// </summary>
public sealed class TypeScriptCodeGenerator
{
    private int _indentLevel;

    /// <summary>
    ///     创建 TypeScript 代码生成器
    /// </summary>
    public TypeScriptCodeGenerator()
    {
        Options = new TypeScriptGeneratorOptions();
    }

    /// <summary>
    ///     创建 TypeScript 代码生成器
    /// </summary>
    /// <param name="options">生成选项</param>
    public TypeScriptCodeGenerator(TypeScriptGeneratorOptions options)
    {
        Options = options;
    }

    /// <summary>
    ///     生成选项
    /// </summary>
    public TypeScriptGeneratorOptions Options { get; }

    /// <summary>
    ///     生成 TypeScript 渲染模块源码
    /// </summary>
    /// <param name="nodes">优化后的模板节点列表</param>
    /// <param name="templateName">模板名称（用于函数命名）</param>
    /// <returns>TypeScript 源码</returns>
    public string Generate(IReadOnlyList<DejaVuTemplateNode> nodes, string templateName = "render")
    {
        var sb = new StringBuilder();

        GenerateHeader(sb);
        GenerateRenderFunction(sb, nodes, templateName);
        GenerateHelperFunctions(sb);

        return sb.ToString();
    }

    private void GenerateHeader(StringBuilder sb)
    {
        if (Options.IncludeHeader)
        {
            sb.AppendLine("// Auto-generated by DejaVu TypeScript Code Generator");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine();
        }

        if (Options.EmitHelpersInline)
        {
            sb.AppendLine("type TemplateContext = Record<string, any>;");
            sb.AppendLine();
        }
    }

    private void GenerateRenderFunction(StringBuilder sb, IReadOnlyList<DejaVuTemplateNode> nodes, string funcName)
    {
        sb.AppendLine($"export function {funcName}(ctx: TemplateContext): string {{");
        _indentLevel = 1;

        Indent(sb);
        sb.AppendLine("const parts: string[] = [];");

        foreach (var node in nodes)
        {
            GenerateNode(sb, node);
        }

        Indent(sb);
        sb.AppendLine("return parts.join('');");

        _indentLevel = 0;
        sb.AppendLine("}");
    }

    private void GenerateNode(StringBuilder sb, DejaVuTemplateNode node)
    {
        switch (node)
        {
            case DejaVuTextNode textNode:
                GenerateTextNode(sb, textNode);
                break;
            case DejaVuCodeNode codeNode:
                GenerateCodeNode(sb, codeNode);
                break;
            case DejaVuIfNode ifNode:
                GenerateIfNode(sb, ifNode);
                break;
            case DejaVuLoopNode loopNode:
                GenerateLoopNode(sb, loopNode);
                break;
            case DejaVuLetNode letNode:
                GenerateLetNode(sb, letNode);
                break;
            case DejaVuWithNode withNode:
                GenerateWithNode(sb, withNode);
                break;
            case DejaVuBlockNode blockNode:
                GenerateBlockNode(sb, blockNode);
                break;
            case DejaVuExtendsNode extendsNode:
                GenerateExtendsNode(sb, extendsNode);
                break;
            case DejaVuIncludeNode includeNode:
                GenerateIncludeNode(sb, includeNode);
                break;
            case DejaVuSuperNode:
                GenerateSuperNode(sb);
                break;
            case DejaVuRawNode rawNode:
                GenerateRawNode(sb, rawNode);
                break;
            case DejaVuMatchNode matchNode:
                GenerateMatchNode(sb, matchNode);
                break;
        }
    }

    private void GenerateTextNode(StringBuilder sb, DejaVuTextNode textNode)
    {
        var escaped = EscapeTsString(textNode.Text);
        Indent(sb);
        sb.AppendLine($"parts.push(\"{escaped}\");");
    }

    private void GenerateCodeNode(StringBuilder sb, DejaVuCodeNode codeNode)
    {
        var expr = GenerateExpression(codeNode.ParsedExpression, codeNode.Code);
        Indent(sb);
        sb.AppendLine($"parts.push(escapeHtml(String({expr} ?? '')));");
    }

    private void GenerateIfNode(StringBuilder sb, DejaVuIfNode ifNode)
    {
        var condition = GenerateExpression(ifNode.ParsedCondition, ifNode.Condition);
        Indent(sb);
        sb.AppendLine($"if (toBoolean({condition})) {{");

        _indentLevel++;
        foreach (var child in ifNode.Children)
        {
            GenerateNode(sb, child);
        }

        _indentLevel--;

        foreach (var elseIfNode in ifNode.ElseIfNodes)
        {
            var elseIfCondition = GenerateExpression(elseIfNode.ParsedCondition, elseIfNode.Condition);
            Indent(sb);
            sb.AppendLine($"}} else if (toBoolean({elseIfCondition})) {{");

            _indentLevel++;
            foreach (var child in elseIfNode.Children)
            {
                GenerateNode(sb, child);
            }

            _indentLevel--;
        }

        if (ifNode.ElseChildren.Count > 0)
        {
            Indent(sb);
            sb.AppendLine("} else {");

            _indentLevel++;
            foreach (var child in ifNode.ElseChildren)
            {
                GenerateNode(sb, child);
            }

            _indentLevel--;
        }

        Indent(sb);
        sb.AppendLine("}");
    }

    private void GenerateLoopNode(StringBuilder sb, DejaVuLoopNode loopNode)
    {
        var iterable = GenerateExpression(loopNode.ParsedExpression, loopNode.Expression);
        var itemName = loopNode.ItemName ?? "item";

        Indent(sb);
        sb.AppendLine($"for (const {itemName} of (toIterable({iterable}))) {{");

        _indentLevel++;
        Indent(sb);
        sb.AppendLine("const __loopCtx = { ...ctx, " + itemName + $", index: __loopIndex++ }};");

        foreach (var child in loopNode.Children)
        {
            GenerateNodeWithCtx(sb, child, "__loopCtx");
        }

        _indentLevel--;
        Indent(sb);
        sb.AppendLine("}");
    }

    private void GenerateLetNode(StringBuilder sb, DejaVuLetNode letNode)
    {
        var value = GenerateExpression(letNode.ParsedExpression, letNode.Expression);
        Indent(sb);
        sb.AppendLine($"const __letCtx = {{ ...ctx, {letNode.VariableName}: {value} }};");

        foreach (var child in letNode.Children)
        {
            GenerateNodeWithCtx(sb, child, "__letCtx");
        }
    }

    private void GenerateWithNode(StringBuilder sb, DejaVuWithNode withNode)
    {
        var obj = GenerateExpression(withNode.ParsedExpression, withNode.Expression);
        Indent(sb);
        sb.AppendLine($"const __withObj = {obj};");

        Indent(sb);
        sb.AppendLine("const __withCtx = { ...ctx, ...(__withObj instanceof Object ? __withObj : {}) };");

        foreach (var child in withNode.Children)
        {
            GenerateNodeWithCtx(sb, child, "__withCtx");
        }
    }

    private void GenerateBlockNode(StringBuilder sb, DejaVuBlockNode blockNode)
    {
        Indent(sb);
        sb.AppendLine($"// block: {blockNode.Name}");

        foreach (var child in blockNode.Children)
        {
            GenerateNode(sb, child);
        }
    }

    private void GenerateExtendsNode(StringBuilder sb, DejaVuExtendsNode extendsNode)
    {
        var parent = extendsNode.ParentTemplate.Trim('\'', '"');
        Indent(sb);
        sb.AppendLine($"// extends: {EscapeTsString(parent)}");
    }

    private void GenerateIncludeNode(StringBuilder sb, DejaVuIncludeNode includeNode)
    {
        var path = includeNode.TemplatePath.Trim('\'', '"');
        Indent(sb);
        sb.AppendLine($"parts.push(renderInclude(ctx, \"{EscapeTsString(path)}\"));");
    }

    private void GenerateSuperNode(StringBuilder sb)
    {
        Indent(sb);
        sb.AppendLine("parts.push(renderSuper(ctx));");
    }

    private void GenerateRawNode(StringBuilder sb, DejaVuRawNode rawNode)
    {
        foreach (var child in rawNode.Children)
        {
            if (child is DejaVuTextNode textNode)
            {
                var escaped = EscapeTsString(textNode.Text);
                Indent(sb);
                sb.AppendLine($"parts.push(\"{escaped}\");");
            }
            else if (child is DejaVuCodeNode codeNode)
            {
                var expr = GenerateExpression(codeNode.ParsedExpression, codeNode.Code);
                Indent(sb);
                sb.AppendLine($"parts.push(String({expr} ?? ''));");
            }
        }
    }

    private void GenerateMatchNode(StringBuilder sb, DejaVuMatchNode matchNode)
    {
        var matchExpr = GenerateExpression(matchNode.ParsedExpression, matchNode.Expression);
        Indent(sb);
        sb.AppendLine($"const __matchVal = {matchExpr};");

        var isFirst = true;
        foreach (var child in matchNode.Children)
        {
            if (child is DejaVuIfNode ifNode)
            {
                var condition = GenerateExpression(ifNode.ParsedCondition, ifNode.Condition);
                var keyword = isFirst ? "if" : "} else if";
                Indent(sb);
                sb.AppendLine($"{keyword} (areEqual(__matchVal, {condition})) {{");

                _indentLevel++;
                foreach (var ifChild in ifNode.Children)
                {
                    GenerateNode(sb, ifChild);
                }

                _indentLevel--;
                isFirst = false;
            }
        }

        if (!isFirst)
        {
            Indent(sb);
            sb.AppendLine("}");
        }
    }

    private void GenerateNodeWithCtx(StringBuilder sb, DejaVuTemplateNode node, string ctxVar)
    {
        switch (node)
        {
            case DejaVuTextNode textNode:
                var escaped = EscapeTsString(textNode.Text);
                Indent(sb);
                sb.AppendLine($"parts.push(\"{escaped}\");");
                break;
            case DejaVuCodeNode codeNode:
                var expr = GenerateExpression(codeNode.ParsedExpression, codeNode.Code);
                Indent(sb);
                sb.AppendLine($"parts.push(escapeHtml(String({expr} ?? '')));");
                break;
            default:
                Indent(sb);
                sb.AppendLine($"// TODO: nested {node.NodeType} in scoped context");
                break;
        }
    }

    private string GenerateExpression(IExpressionNode? parsedAst, string fallback)
    {
        if (parsedAst != null)
        {
            return GenerateExpressionNode(parsedAst);
        }

        return GenerateFallbackExpression(fallback);
    }

    private string GenerateExpressionNode(IExpressionNode node)
    {
        return node switch
        {
            LiteralNode lit => GenerateLiteral(lit),
            IdentifierNode id => $"ctx[\"{id.Name}\"]",
            BinaryNode binary => GenerateBinary(binary),
            UnaryNode unary => GenerateUnary(unary),
            MemberAccessNode member => GenerateMemberAccess(member),
            CallNode call => GenerateCall(call),
            IndexNode index => GenerateIndex(index),
            PipeNode pipe => GeneratePipe(pipe),
            _ => "undefined"
        };
    }

    private string GenerateLiteral(LiteralNode lit)
    {
        return lit.Value switch
        {
            null => "null",
            bool b => b ? "true" : "false",
            double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
            string s => $"\"{EscapeTsString(s)}\"",
            _ => $"\"{EscapeTsString(lit.Value.ToString())}\""
        };
    }

    private string GenerateBinary(BinaryNode binary)
    {
        var left = GenerateExpressionNode(binary.Left);
        var right = GenerateExpressionNode(binary.Right);

        return binary.Operator switch
        {
            BinaryOperator.Add => $"({left} + {right})",
            BinaryOperator.Subtract => $"({left} - {right})",
            BinaryOperator.Multiply => $"({left} * {right})",
            BinaryOperator.Divide => $"({left} / {right})",
            BinaryOperator.Modulo => $"({left} % {right})",
            BinaryOperator.Equal => $"({left} === {right})",
            BinaryOperator.NotEqual => $"({left} !== {right})",
            BinaryOperator.LessThan => $"({left} < {right})",
            BinaryOperator.LessThanOrEqual => $"({left} <= {right})",
            BinaryOperator.GreaterThan => $"({left} > {right})",
            BinaryOperator.GreaterThanOrEqual => $"({left} >= {right})",
            BinaryOperator.And => $"({left} && {right})",
            BinaryOperator.Or => $"({left} || {right})",
            _ => "undefined"
        };
    }

    private string GenerateUnary(UnaryNode unary)
    {
        var operand = GenerateExpressionNode(unary.Operand);
        return unary.Operator switch
        {
            UnaryOperator.Negate => $"(-{operand})",
            UnaryOperator.Not => $"(!{operand})",
            _ => operand
        };
    }

    private string GenerateMemberAccess(MemberAccessNode member)
    {
        var obj = GenerateExpressionNode(member.Object);
        return $"{obj}[\"{member.MemberName}\"]";
    }

    private string GenerateCall(CallNode call)
    {
        var func = GenerateExpressionNode(call.Function);
        var args = string.Join(", ", call.Arguments.Select(GenerateExpressionNode));
        return $"(typeof {func} === 'function' ? {func}({args}) : undefined)";
    }

    private string GenerateIndex(IndexNode index)
    {
        var obj = GenerateExpressionNode(index.Object);
        var idx = GenerateExpressionNode(index.Index);
        return $"{obj}[{idx}]";
    }

    private string GeneratePipe(PipeNode pipe)
    {
        var left = GenerateExpressionNode(pipe.Left);
        var args = string.Join(", ", pipe.Arguments.Select(GenerateExpressionNode));
        return $"applyFilter(\"{pipe.FilterName}\", {left}{(string.IsNullOrEmpty(args) ? "" : $", {args}")})";
    }

    private string GenerateFallbackExpression(string expression)
    {
        return $"evalExpr(ctx, \"{EscapeTsString(expression)}\")";
    }

    private void GenerateHelperFunctions(StringBuilder sb)
    {
        if (!Options.EmitHelpersInline)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("function escapeHtml(input: string): string {");
        sb.AppendLine("    return input");
        sb.AppendLine("        .replace(/&/g, '&amp;')");
        sb.AppendLine("        .replace(/</g, '&lt;')");
        sb.AppendLine("        .replace(/>/g, '&gt;')");
        sb.AppendLine("        .replace(/\"/g, '&quot;')");
        sb.AppendLine("        .replace(/'/g, '&#x27;');");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function toBoolean(value: any): boolean {");
        sb.AppendLine("    if (value === null || value === undefined) return false;");
        sb.AppendLine("    if (typeof value === 'boolean') return value;");
        sb.AppendLine("    return true;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function toIterable(value: any): any[] {");
        sb.AppendLine("    if (Array.isArray(value)) return value;");
        sb.AppendLine("    if (value instanceof Object) return Object.entries(value);");
        sb.AppendLine("    return [];");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function areEqual(a: any, b: any): boolean {");
        sb.AppendLine("    if (a === b) return true;");
        sb.AppendLine("    if (a === null || b === null) return false;");
        sb.AppendLine("    return String(a) === String(b);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function applyFilter(name: string, value: any, ...args: any[]): any {");
        sb.AppendLine("    const filters: Record<string, (v: any, ...a: any[]) => any> = {");
        sb.AppendLine("        uppercase: (v) => String(v).toUpperCase(),");
        sb.AppendLine("        lowercase: (v) => String(v).toLowerCase(),");
        sb.AppendLine("        trim: (v) => String(v).trim(),");
        sb.AppendLine("        capitalize: (v) => { const s = String(v); return s.charAt(0).toUpperCase() + s.slice(1); },");
        sb.AppendLine("        truncate: (v, len) => { const s = String(v); return s.length > len ? s.slice(0, len) + '...' : s; },");
        sb.AppendLine("        default: (v, d) => (v === null || v === undefined || v === '') ? d : v,");
        sb.AppendLine("        join: (v, sep) => Array.isArray(v) ? v.join(sep ?? ', ') : String(v),");
        sb.AppendLine("        length: (v) => Array.isArray(v) ? v.length : String(v).length,");
        sb.AppendLine("        first: (v) => Array.isArray(v) ? v[0] : undefined,");
        sb.AppendLine("        last: (v) => Array.isArray(v) ? v[v.length - 1] : undefined,");
        sb.AppendLine("        reverse: (v) => Array.isArray(v) ? [...v].reverse() : String(v).split('').reverse().join(''),");
        sb.AppendLine("        sort: (v) => Array.isArray(v) ? [...v].sort() : v,");
        sb.AppendLine("        strip_html: (v) => String(v).replace(/<[^>]*>/g, ''),");
        sb.AppendLine("        escape: (v) => escapeHtml(String(v)),");
        sb.AppendLine("        newline_to_br: (v) => String(v).replace(/\\n/g, '<br/>'),");
        sb.AppendLine("    };");
        sb.AppendLine("    const fn = filters[name];");
        sb.AppendLine("    return fn ? fn(value, ...args) : value;");
        sb.AppendLine("}");
    }

    private void Indent(StringBuilder sb)
    {
        sb.Append(new string(' ', _indentLevel * Options.IndentSize));
    }

    private static string EscapeTsString(string? input)
    {
        if (input == null) return string.Empty;
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}

/// <summary>
///     TypeScript 代码生成选项
/// </summary>
public sealed class TypeScriptGeneratorOptions
{
    /// <summary>
    ///     是否包含文件头注释
    /// </summary>
    public bool IncludeHeader { get; init; } = true;

    /// <summary>
    ///     是否内联辅助函数（escapeHtml/toBoolean/toIterable/areEqual/applyFilter）
    /// </summary>
    public bool EmitHelpersInline { get; init; } = true;

    /// <summary>
    ///     缩进空格数
    /// </summary>
    public int IndentSize { get; init; } = 4;
}
